### ISSUE TITLE
Seed

### ISSUE THREAD

**Issue by tobsn** [leroy-merlin-br/mongolid-laravel#1]
what's the easiest way to use mongolid to seed data with artisan?

thanks!

**Comment by ahsenx** [comment]
Migrations are working for https://github.com/jenssegers/laravel-mongodb/

**Comment by tobsn** [comment]
@janporu-san he's right, we never used migrations as you would use migrations with mysql.
@kodeine example? I can't find one :/

**Comment by kodeine** [comment]
@tobsn take a look at laravel-mongodb/src/Jenssegers/Mongodb/Schema/

**Comment by ravanscafi** [comment]
Fixed in #119
