### ISSUE TITLE
Minification, Manual join(), custom Migration Class, Events, Validation

### ISSUE THREAD

**Issue by tobsn** [leroy-merlin-br/mongolid-laravel#10]
we're looking into forking and putting in something like this for minification:
https://github.com/marcqualie/mongominify/wiki/Getting-Started

creating a chainable ->join() method for joining other collections into the current object that relates the models id back to the joined model
ergo Users::find(array('name'=>'jackson'))->join( 'Posts' ) would take users _id and try to match it up in Posts user_id.

adding a custom migration class to replace the original one to use mongo as migration data/information storage.

adding events:
beforeCreate
beforeCreateNew
afterCreate
afterCreateNew
beforeSave
beforeSaveNew
afterSave
afterSaveNew
beforeValidation
afterValidation
beforeDestroy

Validation for Mongo: https://github.com/navruzm/laravel-mongo-validation

any plans on your side to do this?

**Comment by ravanscafi** [comment]
No use-case and plans for minification right now.

**Comment by tobsn** [comment]
> commented on Jun 15, 2013

5+ years for a reply :D
