### ISSUE TITLE
Support and Branch strategy

### ISSUE THREAD

**Issue by gmsantos** [leroy-merlin-br/mongolid-laravel#100]
Before v2.0 we should define how our branchs will be organized.

Topics to discus:
- Use master branch for stable and develop for vNext
- Should we increase minor versions for Laravel releases ?
- What Laravel versions we will support?
- For old versions supports, a legacy branch will be maintained?

**Comment by ravanscafi** [comment]
closing as we dropped the `develop` branch and only using master.
