### ISSUE TITLE
Does not install if mongodb is not running on same host

### ISSUE THREAD

**Issue by priyolahiri** [leroy-merlin-br/mongolid-laravel#25]
Output when doing composer install if mongodb is not running on same host. Same result even if  default config has been provided for different host in database.php

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
{"error":{"type":"ErrorException","message":"Failed to connect with string: \"mongodb:\/\/127.0.0.1:27017\/mongolid\"","file":"\/home\/jscore\/webhosts\/jscore_ent_api\/vendor\/zizaco\/mongolid\/src\/Zizaco\/Mongolid\/MongoDbConnector.php","line":30}}Script php artisan optimize handling the post-install-cmd event returned with an error

  [RuntimeException]
  Error Output:

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader]

**Comment by rscafi** [comment]
You can change the connection on the config file.
Please check https://github.com/leroy-merlin-br/mongolid-laravel#installation
