### ISSUE TITLE
Embed-Many querying

### ISSUE THREAD

**Issue by samuelcasas** [leroy-merlin-br/mongolid-laravel#30]
Hi, is it possible to find a embedded document to do an update (for example), because im trying to do a simple ``` $ad->images()->find(1234); ``` and it throws me a ```Call to a member function find() on a non-object```. if is possible to query in the embedded documents?? or there's another way to achieve this.

Thanks.

**Comment by GuilhermeGuitte** [comment]
Moving to `mongolid` issues.
