### ISSUE TITLE
Regex example

### ISSUE THREAD

**Issue by duffybelfield** [leroy-merlin-br/mongolid-laravel#34]
Hey there!

How would I replicate this using your package?

db.users.find({'$or':[{first_name: { $regex: /chris/i }}, {last_name: { $regex: /chris/i }}]});

Thanks!

**Comment by GuilhermeGuitte** [comment]
```
YourModel::where(['$or' => [ ['first_name' => new MongoRegex('/chris/')],  ['last_name' => new MongoRegex('/chris/') ]]]);
```

See:

http://php.net/manual/pt_BR/class.mongoregex.php
