### ISSUE TITLE
OR on where

### ISSUE THREAD

**Issue by duffybelfield** [leroy-merlin-br/mongolid-laravel#35]
Trying to create this query:

db.users.find({'$or':[{first_name: { $regex: /chris/i }}, {last_name: { $regex: /chris/i }}]});

How would I do that currently got:

$result = $user->where(array(['first_name' => ['$regex' => $regexp ]], ['last_name' => ['$regex' => $regexp ]]));

**Comment by GuilhermeGuitte** [comment]
See:

https://github.com/leroy-merlin-br/mongolid-laravel/issues/34
