### ISSUE TITLE
Database [mongodb] not configured.

### ISSUE THREAD

**Issue by Irto** [leroy-merlin-br/mongolid-laravel#39]
InvalidArgumentException
Database [mongodb] not configured.

/home/irto/Projetos/www/phonerio/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php : 171

It's seem that Illuminate\Validation\Validator try to use a Driver for verify if tha field is unique on database.

**Comment by cosmasmallya** [comment]
I don't understand you, Irto. Have you changed 'connections' array as in renaming it to 'main' or how exactly?

**Comment by Irto** [comment]
From connections key. MongoLid had to stay in same level of connection key on ```database.php``` configuration file.

**Comment by luongs3** [comment]
It's not working

**Comment by andresenra** [comment]
Just rebuild your config cache:
`artisan config:cache`

(leave the mongodb connection inside your connections array, as it is supposed to be).

**Comment by wajdijurry** [comment]
> Just rebuild your config cache:
> `artisan config:cache`
> 
> (leave the mongodb connection inside your connections array, as it is supposed to be).

I did as you suggested, but I got this error now:
```
Undefined index: driver
```
