### ISSUE TITLE
Delete function Issue

### ISSUE THREAD

**Issue by oaloria** [leroy-merlin-br/mongolid-laravel#45]
Hi there.

I just found an issue on delete function.
Here is the code:

```
$Model = new \Content\Models\Blocks;
$data = $Model->find( "52ebb8d407983b3816000000" );
$data->delete();
```

It finds the object fine and on delete returns true, but doesn't delete the object.
This issue happens when you have an object embeded with empty content like this:

```
{
  _id: ObjectId("52ebb8d407983b3816000000"),
  name: "TestClient",
  data: {},
  token: "TestClient",
  created_at: ISODate("2014-01-31T14:53:08Z"),
  updated_at: ISODate("2014-01-31T14:53:08Z")
}
```

(data: {}) generates the issue, if you remove that attribute, then delete works fine.

To make sure it's a mongolid issue I did a direct delete to the database using Mongo-PHP ->remove function and it worked properly.

Thanks in advance.

**Comment by ravanscafi** [comment]
I've just tried it now and it worked. Perhaps it was fixed in the past few years :laughing:

**Comment by oaloria** [comment]
Glad someone comment it out.
¯\_(ツ)_/¯

**Comment by ravanscafi** [comment]
Better late than never, I guess, sorry :sweat_smile:
Taking care of the issues and preparing for a new version in the next months :)

**Comment by oaloria** [comment]
Awesome! Sadly I'm not working on that project anymore, so I have no more feedback.
Keep going!
