### ISSUE TITLE
The $hidden property in Models isn't taken into account

### ISSUE THREAD

**Issue by nsebban** [leroy-merlin-br/mongolid-laravel#48]
Hello,

Eloquent models have a $hidden property that allows to exclude a list of specific fields from being dumped in an array or JSON conversion. It is documented in the [Eloquent docs](http://laravel.com/docs/eloquent#converting-to-arrays-or-json).

In Mongolid, every field seems to be dumped in arrays or JSON conversions, even though I did set a list of fields in the $hidden property.

```php
// Basic model
class User extends MongoLid implements UserInterface
{
	public $hidden = array('_id', 'password');
}

// Instance
$myUser = User::where(['email' => 'abc@abc.com'])->first();

// Data dump as JSON
dd($myUser->toJSON());

// Fields '_id' and 'password' are dumped even though they're listed in the $hidden property
// {"_id":{"$id":"52f4b1b1140ba0ee61c5bce8"},"email":"abc@abc.com","password":"$2y$10$eVn5tr1vKiwYtRTKM9sRWOXqC1LEFoCxX1LmsLUWZqr2Pv8TSk4AC"}
```

Is there something I don't get ? Or is it an issue ?

Thanks in advance.

**Comment by rscafi** [comment]
Hi, please refer to leroy-merlin-br/mongolid#25
