### ISSUE TITLE
composer install problem

### ISSUE THREAD

**Issue by doespresso** [leroy-merlin-br/mongolid-laravel#49]
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for zizaco/mongolid-laravel dev-master -> satisfiable by zizaco/mongolid-laravel[dev-master].
    - zizaco/mongolid-laravel dev-master requires zizaco/mongolid dev-master -> no matching package found.

**Comment by rscafi** [comment]
We are going to fix it soon, when launching new version.
