### ISSUE TITLE
About Model::referencesMany($model, $field, $cachable = true) 

### ISSUE THREAD

**Issue by smaeda** [leroy-merlin-br/mongolid-laravel#56]
Thank you for your good library.

I used referencesMany() in my Mongolid class. I defined correctly?
For a typical relationship example in http://docs.mongodb.org/manual/core/data-modeling-introduction/#references, I defined following.

``` User.php
class User extends Mongolid {
    protected $collection = 'Users';
    public function contacts(){
        return $this->referencesMany('Contact', '_id');
    }
}
```

But it was not good, interpreter said

```
Symfony \ Component \ Debug \ Exception \ FatalErrorException
Cannot use object of type MongoId as array
```

at line 553 in Model.php.

Did I use it correctly? Any hints, please.

**Comment by ravanscafi** [comment]
You should refer to a field to store the contacts, not which contact field to use (`_id`), ids are always used on references.

Think of something like it:

```php
class Contact extends \MongolidLaravel\MongolidModel {
    protected $collection = 'contacts';
}

class User extends \MongolidLaravel\MongolidModel {
    protected $collection = 'users';

    public function contacts(){
        return $this->referencesMany(Contact::class, 'contacts');
    }
}
```

and then use it like this:

```php
$contact = new Contact();
// update some contact fields and save it

$user = new User();
$user->attach('contacts', $contact);
$user->save();
```
