### ISSUE TITLE
Usage of detach and polymorph

### ISSUE THREAD

**Issue by Solidary** [leroy-merlin-br/mongolid-laravel#61]
Please how to use the polymorphism in MongoLid ? I have a class Section and Question which inherit of another one class Item. Section and Question document must be saved into the same collection with a field display which contains "question" if it's a Question document and "section" if it's a Section document. 
How to implement it please ?

I have a document call Item create by an User. I use referencesMany to save the reference of the document created by the user connected. The problem is when I want to deleted the Item created by the user and delete the reference in the document User. How to do it please ?

Thanks...

**Comment by ravanscafi** [comment]
We have plans to update the documentation, and it will cover this questions. :wink:
