### ISSUE TITLE
Update an embedded document

### ISSUE THREAD

**Issue by Solidary** [leroy-merlin-br/mongolid-laravel#62]
Hi,

Pleased how to update an embedded document ? 
When I modify the different field of the embedded class, I don't know how to bind it with the original document and nothing happens when I call the save function on the class object.

How to solve this problem ?

**Comment by rscafi** [comment]
You need to re-embed it to the class.

```
$address = $user->address;
$address->street = 'New Street';
$user->embed('address', $address);
$user->save();
```
