### ISSUE TITLE
Automatically populate a relationship

### ISSUE THREAD

**Issue by maelfosso** [leroy-merlin-br/mongolid-laravel#69]
Hi,

How to populate a relationship automatically ? 
If I have a One-to-Many relationship between User and Comment. An user has many comments.
How could I do if I would like to have Comment object with associated User object instead of just the id using this query.
```
$comments = Comment::all();
```
or to have Comment object using this code
```
$users = User::all()
```

**Comment by rscafi** [comment]
Please check [MongoLid Relationships](http://leroy-merlin-br.github.io/mongolid/relationships/), it's explained there.
