### ISSUE TITLE
Multiple databases/connections

### ISSUE THREAD

**Issue by Flambe** [leroy-merlin-br/mongolid-laravel#71]
I've been trying to connect to two different databases, but I'm getting a 502 bad gateway error. What I've tried is adding two entries into the database.php file and adding in a $connection property to my model.

``` php
    'mongodb' => array(
        'default' => array(
            'host'     => 'localhost',
            'port'     => 27017,
            'database' => 'default',
            'username'     => '',
            'password'     => '',
        ),

        'other-db' => array(
            'host'     => 'localhost',
            'port'     => 27017,
            'database' => 'other-db',
            'username'     => '',
            'password'     => '',
        ),
    ),
```

``` php
class AccountApp extends MongoLid
{
    public $collection = 'account_app';

    public $connection = 'other-db';
} 
```

Is it possible to have two different connections?

**Comment by Flambe** [comment]
After looking though the code a little bit, I found that I can override the database by overriding the __construct of MongoLid.

```php
class AccountApp extends MongoLid
{
    public $collection = 'account_app';

    public function __construct()
    {
        $this->database = 'other-db';
        parent::__construct();
    }
}
```

Would it be possible to get support for specifying a new $connection? If not, this works fine at the moment!

**Comment by ravanscafi** [comment]
As discussed on https://github.com/leroy-merlin-br/mongolid-laravel/pull/79
