### ISSUE TITLE
Laravel 5 Support

### ISSUE THREAD

**Issue by clarkeash** [leroy-merlin-br/mongolid-laravel#72]
Do you have any plans to update your providers to work with Laravel 5?

**Comment by shehi** [comment]
Guess he doesn't.

**Comment by clarkeash** [comment]
I managed to make it work, I could potentially do a pull request when I get time

**Comment by clarkeash** [comment]
Looks like there is a open PR #73 anyway

**Comment by saran87** [comment]
@leroy-merlin-br could you please merge PR #73  changes and close this issue.
