### ISSUE TITLE
Class 'MongoClient' not found

### ISSUE THREAD

**Issue by Vilochane** [leroy-merlin-br/mongolid-laravel#76]
This exceptions throws when extension mongodb installed, 
FatalErrorException in MongoDbConnector.php line 73:
Class 'MongoClient' not found

Had to modify  MongoDbConnector as below

```php
class MongoDbConnector
{
      protected function newMongoClient($connectionString)
      {
         return new MongoDB\Driver\Manager($connectionString);
     }
}
```

**Comment by gmsantos** [comment]
We currently only support legacy mongo extension.

In the future we will support mongodb extension on mongolid.
