### ISSUE TITLE
Search with aggretation and commands

### ISSUE THREAD

**Issue by IgorDePaula** [leroy-merlin-br/mongolid-laravel#88]
I need search data with geolocation (I chosen mongodb by this cause). Read the code, this module/component not has this support. I suggest suport this feature: search with geolocation (using aggregation framework mongo and/or runCommand).

**Comment by rscafi** [comment]
Although this is a cool and useful feature, I guess that it's not up to an ODM to do this. But I can easily be wrong. What is your use case?

**Comment by IgorDePaula** [comment]
Search using geolocation data (using function like geoNear by example). My case is search restaurants by nome and proximity of my user.

**Comment by ravanscafi** [comment]
Duplicated 
https://github.com/leroy-merlin-br/mongolid/issues/23
