### ISSUE TITLE
Possible on PHP 5?

### ISSUE THREAD

**Issue by blackmamb41** [leroy-merlin-br/mongolid-laravel#91]
It's working on php 5.6 ??

i have been read on documentation, minimum requirement it's php 7

**Comment by blackmamb41** [comment]
And it's not working on Laravel 5.2?,. i try to adding class MongolidLaravel\MongolidServiceProvider::class, on config/app.php it's not working

**Comment by rscafi** [comment]
No, the latest version is not compatible with PHP 5.6. It's minimum version is really PHP 7.

About Laravel version, I'll have to confirm.

**Comment by blackmamb41** [comment]
@rscafi Thanks for info
