### ISSUE TITLE
composer install problem with laravel v5.4.23 

### ISSUE THREAD

**Issue by Vittalks** [leroy-merlin-br/mongolid-laravel#96]
Problem 1
    - Installation request for leroy-merlin-br/mongolid-laravel 2.0.0-beta6 -> satisfiable by leroy-merlin-br/mongolid-laravel[v2.0.0-beta6].
    - leroy-merlin-br/mongolid-laravel v2.0.0-beta6 requires leroy-merlin-br/mongolid 2.0.0-beta12 -> satisfiable by leroy-merlin-br/mongolid[v
2.0.0-beta12] but these conflict with your requirements or minimum-stability.

Which package version will support with laravel 5.4.23?

**Comment by diegofelix** [comment]
Hi @Vittalks.

We are actually making mongolid works with 5.2 for now. As soon as we finish, we are going to work on 5.3 and 5.4 versions.

Feel free to help us with the upgrade.

Thanks!

**Comment by emanuellarini** [comment]
The doc says: 
> Note: Mongolid Laravel 2.0 only supports Laravel 5.4+. For older versions use the tags:

So, the "5.4+" part is a typo?

Also, congrats updating the package.. it is awesome!

**Comment by gmsantos** [comment]
@emanuellarini 2.0 is not released yet
